---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabg
spec:
  template:
    spec:
      containers:
      - name: simply-nginx
        volumeMounts:
        - name: fabg-nginx-conf
          mountPath: /etc/nginx/sites-enabled/fabg.conf
          subPath: fabg.conf
      volumes:
      - name: fabg-nginx-conf
        configMap:
          name: fabg-nginx-conf
