---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabg
spec:
  template:
    spec:
      containers:
      - name: fabg
        image: asia.gcr.io/boot-ads/fabg:latest
      - name: fabg-admin
        image: asia.gcr.io/boot-ads/fabg-admin:latest
