---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fabg-nginx-conf
data:
  fabg.conf: |-

    upstream admin_backend {
        server production-fabg:8000;
        keepalive 64;
    }

    upstream public_backend {
        server production-fabg:8080;
        keepalive 64;
    }

    server {
        listen 80; listen [::]:80;

        server_name localhost;
        root /apps/fabg-shared;

        access_log /dev/stdout main;
        error_log /dev/stderr error;

        # set_real_ip_from    10.1.0.0/16;
        # real_ip_header      X-Forwarded-For;

        if ($http_x_forwarded_proto = "http") {
            return 301 https://$host$request_uri;
        }

        location / {
            proxy_pass http://public_backend;
        }

        location /admin {
            proxy_pass http://admin_backend;
        }

        location ~ ^/assets/ {
            access_log off;
        }
    }
