---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fabg-nginx-conf
data:
  fabg.conf: |-

    upstream admin_backend {
        server 127.0.0.1:8000; # server production-fabg:8000;
        keepalive 64;
    }

    upstream public_backend {
        server 127.0.0.1:8080; # server production-fabg:8080;
        keepalive 64;
    }

    proxy_cache_path /var/cache/nginx/cache levels=1:2 keys_zone=fabgkey:8m max_size=500m inactive=10m;
    proxy_temp_path /var/cache/nginx/tmp;

    server {
        listen 80; listen [::]:80;

        server_name localhost;
        root /apps/fabg-shared;

        access_log /dev/stdout main;
        error_log /dev/stderr error;

        # set_real_ip_from    10.1.0.0/16;
        # real_ip_header      X-Forwarded-For;

        if ($http_x_forwarded_proto = "http") {
            return 301 https://$host$request_uri;
        }

        location /admin {
            proxy_pass http://admin_backend;
        }

        location / {
            proxy_ignore_headers     Cache-Control;
            proxy_cache              fabgkey;
            proxy_cache_valid        200 302 5m;
            proxy_cache_valid        404 10m;

            # add_header X-Nginx-Cache $upstream_cache_status;

            proxy_pass http://public_backend;
        }

        location ~ ^/assets/ {
            access_log off;
        }
    }
