---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fabg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fabg
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
